//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchievementUnlock
    {
        public int UserId { get; set; }
        public int AchievementId { get; set; }
        public System.DateTime When { get; set; }
    
        public virtual Achievement Achievement { get; set; }
    }
}
