//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnonymTicketComment
    {
        public int ID { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Message { get; set; }
        public System.DateTime Created { get; set; }
        public string Ip { get; set; }
    
        public virtual User Admin { get; set; }
        public virtual AnonymTicket Ticket { get; set; }
    }
}
