//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnonymTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnonymTicket()
        {
            this.AnonymTicketComments = new HashSet<AnonymTicketComment>();
        }
    
        public int ID { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public int Status { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTime Created { get; set; }
        public int Code { get; set; }
        public string Ip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnonymTicketComment> AnonymTicketComments { get; set; }
        public virtual TicketCategory TicketCategory { get; set; }
        public virtual User Admin { get; set; }
    }
}
