//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crash
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> ScreenshotID { get; set; }
        public Nullable<int> UserID { get; set; }
        public SharedLibrary.Enums.CrashStatus Status { get; set; }
        public string AppVersion { get; set; }
        public Nullable<System.DateTime> Build { get; set; }
        public string LastWindowName { get; set; }
        public string OS { get; set; }
        public Nullable<bool> Is64BitOS { get; set; }
        public Nullable<bool> Is64BitApp { get; set; }
        public System.DateTime Date { get; set; }
        public string Exception { get; set; }
        public string Message { get; set; }
        public string Email { get; set; }
        public string Log { get; set; }
        public bool Enabled { get; set; }
    }
}
