//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaQ
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Question { get; set; }
        public string Response { get; set; }
        public bool IsFirst { get; set; }
    
        public virtual FaqCategory FaqCategory { get; set; }
    }
}
