//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public System.DateTime Uploaded { get; set; }
        public string Name { get; set; }
        public string Hash { get; set; }
        public string Base64 { get; set; }
        public string MIME { get; set; }
        public int Size { get; set; }
    
        private User Owner { get; set; }
    }
}
