//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int FromXP { get; set; }
        public Nullable<int> ToXP { get; set; }
        public string Colour { get; set; }
    }
}
