//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.Guid Code { get; set; }
        public System.DateTime Issue { get; set; }
        public System.DateTime Expiration { get; set; }
        public string Purpose { get; set; }
        public SharedLibrary.Enums.TokenPurpose Type { get; set; }
        public bool Used { get; set; }
    }
}
