//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public int FromID { get; set; }
        public int ToID { get; set; }
        public int ZolikID { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
        public SharedLibrary.Enums.TransactionAssignment Typ { get; set; }
    
        protected virtual User fromUser { get; set; }
        protected virtual User toUser { get; set; }
        public virtual Zolik Zolik { get; set; }
    }
}
