//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebEvent
    {
        public int ID { get; set; }
        public int FromProjectID { get; set; }
        public Nullable<int> FromID { get; set; }
        public int ToID { get; set; }
        public int Type { get; set; }
        public System.DateTime Date { get; set; }
        public bool Enabled { get; set; }
        public string Message { get; set; }
    }
}
