//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZolikType
    {
        public int ID { get; set; }
        public Nullable<int> SplitsToID { get; set; }
        public string Name { get; set; }
        public string FriendlyName { get; set; }
        public bool IsSplittable { get; set; }
        public bool IsTestType { get; set; }
        public bool AllowGive { get; set; }
    
        public virtual ZolikType SplitsTo { get; set; }
    }
}
