//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zolik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zolik()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ID { get; set; }
        public int OwnerID { get; set; }
        public int SubjectID { get; set; }
        public int TeacherID { get; set; }
        public int OriginalOwnerID { get; set; }
        public int TypeID { get; set; }
        public string Title { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime OwnerSince { get; set; }
        public System.DateTime Created { get; set; }
        public string Lock { get; set; }
        public bool AllowSplit { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual User OriginalOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual User Owner { get; set; }
        public virtual User Teacher { get; set; }
        public virtual ZolikType Type { get; set; }
    }
}
