//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Žolíky - aktivace účtu&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* FONTS */
        ///      
        ///            @import url(&apos;https://fonts.googleapis.com/css?family=Montserrat:400,500,700&apos;);
        ///        
        ///
        ///        /* CLIENT-SPECIFIC STYLES */
        ///        body, table, td, a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivateAccount {
            get {
                return ResourceManager.GetString("ActivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;p&gt;
        ///			Následující uživatel se zaregistroval na &lt;a href=&quot;https://www.zoliky.eu/Login&quot;&gt;Žolíkách&lt;/a&gt; &lt;br /&gt;
        ///		&lt;/p&gt;
        ///		&lt;br /&gt;
        ///		&lt;p&gt;
        ///			&lt;b&gt;Informace: &lt;/b&gt; &lt;br /&gt;
        ///			Uživatelské jméno: #Username# &lt;br /&gt;
        ///			Email: #Email# &lt;br /&gt;
        ///			Křestní jméno: #FName# &lt;br /&gt;
        ///			Příjmení: #LName# &lt;br /&gt;
        ///			Třída: #Class# &lt;br /&gt;
        ///			IP: #IP# &lt;br /&gt;
        ///		&lt;/p&gt;
        ///		&lt;br /&gt;
        ///		&lt;p&gt;
        ///			Aktivaci a úpravu uživatele můžete prové [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdminRegistration {
            get {
                return ResourceManager.GetString("AdminRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Žolíky - zapomenuté heslo&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* FONTS */
        ///      
        ///            @import url(&apos;https://fonts.googleapis.com/css?family=Montserrat:400,500,700&apos;);
        ///        
        ///
        ///        /* CLIENT-SPECIFIC STYLES */
        ///        body, table, td [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Joker {
            get {
                object obj = ResourceManager.GetObject("Joker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon JokerIco {
            get {
                object obj = ResourceManager.GetObject("JokerIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Žolíky - Nový žolík&lt;/title&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///        /* FONTS */
        ///		@import url(&apos;https://fonts.googleapis.com/css?family=Montserrat:400,500,700&apos;);
        ///
        ///		/* CLIENT-SPECIFIC STYLES */
        ///
        ///		body, table, td, a {
        ///			-webkit-text-size-adjust: 100%;
        ///			-ms-text-size [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewZolicek {
            get {
                return ResourceManager.GetString("NewZolicek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Žolíky - změna hesla&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* FONTS */
        ///      
        ///            @import url(&apos;https://fonts.googleapis.com/css?family=Montserrat:400,500,700&apos;);
        ///        
        ///
        ///        /* CLIENT-SPECIFIC STYLES */
        ///        body, table, td, a { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Žolíky - aktivace účtu&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* FONTS */
        ///      
        ///            @import url(&apos;https://fonts.googleapis.com/css?family=Montserrat:400,500,700&apos;);
        ///        
        ///
        ///        /* CLIENT-SPECIFIC STYLES */
        ///        body, table, td, a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegisterAccount {
            get {
                return ResourceManager.GetString("RegisterAccount", resourceCulture);
            }
        }
    }
}
